Calculando el coeficiente de correlación Pearson

1. Importar bibliotecas

In [1]:
import pandas as pd
import numpy as np

2. Cargar el dataset

In [ ]:
ruta = ("../data/raw/dataset_7variables_2000_2022.csv")
df = pd.read_csv(ruta)

3. Explorar datos y valores faltantes

In [8]:
df.describe().T.round(1)

,count,mean,std,min,25%,50%,75%,max
year,4244.0,2011.1,6.6,2000.0,2005.0,2011.0,2017.0,2.022000e+03
population,4244.0,76179062.5,539694002.1,9566.0,1921557.8,7382109.5,26096305.8,8.021407e+09
births,4244.0,1495146.1,10502980.1,197.0,31771.8,138645.0,615917.0,1.460549e+08
deaths,4244.0,599805.0,4226299.9,66.0,14227.8,57920.0,201302.0,6.972810e+07
child_deaths_under_5,4244.0,77675.4,564574.1,0.0,323.0,2857.5,23048.0,1.018010e+07
health_percentage,4244.0,6.2,2.8,1.2,4.1,5.7,7.9,2.450000e+01
gdp,4244.0,21716.5,23529.0,712.0,4826.0,13202.0,30472.1,1.490251e+05
life_expectancy,4244.0,70.0,8.7,14.7,64.5,71.4,76.5,8.570000e+01

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4244 entries, 0 to 4243
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   entity                4244 non-null   object
 1   year                  4244 non-null   int64
 2   population            4244 non-null   float64
 3   births                4244 non-null   float64
 4   deaths                4244 non-null   float64
 5   child_deaths_under_5  4244 non-null   int64
 6   health_percentage     4244 non-null   float64
 7   gdp                   4244 non-null   float64
 8   life_expectancy       4244 non-null   float64
dtypes: float64(6), int64(2), object(1)
memory usage: 298.5+ KB

In [11]:
df.isnull().sum()

entity                  0
year                    0
population              0
births                  0
deaths                  0
child_deaths_under_5    0
health_percentage       0
gdp                     0
life_expectancy         0
dtype: int64

4. Seleccionar variables

In [13]:
variables_numericas = ["population",
                       "births",
                       "deaths",
                       "child_deaths_under_5",
                       "health_percentage",
                       "gdp",
                       "life_expectancy"]

In [14]:
df_vn = df[variables_numericas].copy()

In [ ]:
from itertools import combinations
from math import comb

#Calcular el número de combinaciones
n = len(variables_numericas)
total_combinaciones = comb(n, 2)

print(f"Número de combinaciones posibles: {total_combinaciones}")

Número de combinaciones posibles: 21

In [19]:
# inicializamos el arreglo para guardar los resultados
resultados = []

for variable_x, variable_y in combinations(variables_numericas, 2):
    #se calcula r mediante la función corr de pandas
    r = df_vn[variable_x].corr(df_vn[variable_y], method="pearson")

    # se guardan en un arreglo todos los valores obtenidos
    resultados.append([variable_x, variable_y, r, abs(r)])

    # el arreglo de resultados se transforma en df de pandas para manipularlo
    #Convertir los resutltados en un DataFrame
    df_resultados = pd.DataFrame(
        resultados,
        columns=["Variable X",
                 "Variable Y",
                 "Pearson",
                 "Intensidad"] # es el valor absoluto de 4
    )

    #Ordenar por intensidad de mayor a menor
    df_resultados = df_resultados.sort_values(
        by="Intensidad",
        ascending=False
    ).reset_index(drop=True)

    display(df_resultados)

   Variable X Variable Y   Pearson  Intensidad
0  population     births  0.992562    0.992562

   Variable X Variable Y   Pearson  Intensidad
0  population     deaths  0.997836    0.997836
1  population     births  0.992562    0.992562

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1  population                births  0.992562    0.992562
2  population  child_deaths_under_5  0.935124    0.935124

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1  population                births  0.992562    0.992562
2  population  child_deaths_under_5  0.935124    0.935124
3  population     health_percentage -0.016296    0.016296

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1  population                births  0.992562    0.992562
2  population  child_deaths_under_5  0.935124    0.935124
3  population                   gdp -0.030289    0.030289
4  population     health_percentage -0.016296    0.016296

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1  population                births  0.992562    0.992562
2  population  child_deaths_under_5  0.935124    0.935124
3  population                   gdp -0.030289    0.030289
4  population     health_percentage -0.016296    0.016296
5  population       life_expectancy  0.006890    0.006890

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1      births                deaths  0.993034    0.993034
2  population                births  0.992562    0.992562
3  population  child_deaths_under_5  0.935124    0.935124
4  population                   gdp -0.030289    0.030289
5  population     health_percentage -0.016296    0.016296
6  population       life_expectancy  0.006890    0.006890

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1      births                deaths  0.993034    0.993034
2  population                births  0.992562    0.992562
3      births  child_deaths_under_5  0.967222    0.967222
4  population  child_deaths_under_5  0.935124    0.935124
5  population                   gdp -0.030289    0.030289
6  population     health_percentage -0.016296    0.016296
7  population       life_expectancy  0.006890    0.006890

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1      births                deaths  0.993034    0.993034
2  population                births  0.992562    0.992562
3      births  child_deaths_under_5  0.967222    0.967222
4  population  child_deaths_under_5  0.935124    0.935124
5      births     health_percentage -0.030696    0.030696
6  population                   gdp -0.030289    0.030289
7  population     health_percentage -0.016296    0.016296
8  population       life_expectancy  0.006890    0.006890

   Variable X            Variable Y   Pearson  Intensidad
0  population                deaths  0.997836    0.997836
1      births                deaths  0.993034    0.993034
2  population                births  0.992562    0.992562
3      births  child_deaths_under_5  0.967222    0.967222
4  population  child_deaths_under_5  0.935124    0.935124
5      births                   gdp -0.044742    0.044742
6      births     health_percentage -0.030696    0.030696
7  population                   gdp -0.030289    0.030289
8  population     health_percentage -0.016296    0.016296
9  population       life_expectancy  0.006890    0.006890

    Variable X            Variable Y   Pearson  Intensidad
0   population                deaths  0.997836    0.997836
1       births                deaths  0.993034    0.993034
2   population                births  0.992562    0.992562
3       births  child_deaths_under_5  0.967222    0.967222
4   population  child_deaths_under_5  0.935124    0.935124
5       births                   gdp -0.044742    0.044742
6       births     health_percentage -0.030696    0.030696
7   population                   gdp -0.030289    0.030289
8       births       life_expectancy -0.019662    0.019662
9   population     health_percentage -0.016296    0.016296
10  population       life_expectancy  0.006890    0.006890

    Variable X            Variable Y   Pearson  Intensidad
0   population                deaths  0.997836    0.997836
1       births                deaths  0.993034    0.993034
2   population                births  0.992562    0.992562
3       births  child_deaths_under_5  0.967222    0.967222
4       deaths  child_deaths_under_5  0.944894    0.944894
5   population  child_deaths_under_5  0.935124    0.935124
6       births                   gdp -0.044742    0.044742
7       births     health_percentage -0.030696    0.030696
8   population                   gdp -0.030289    0.030289
9       births       life_expectancy -0.019662    0.019662
10  population     health_percentage -0.016296    0.016296
11  population       life_expectancy  0.006890    0.006890

    Variable X            Variable Y   Pearson  Intensidad
0   population                deaths  0.997836    0.997836
1       births                deaths  0.993034    0.993034
2   population                births  0.992562    0.992562
3       births  child_deaths_under_5  0.967222    0.967222
4       deaths  child_deaths_under_5  0.944894    0.944894
5   population  child_deaths_under_5  0.935124    0.935124
6       births                   gdp -0.044742    0.044742
7       births     health_percentage -0.030696    0.030696
8   population                   gdp -0.030289    0.030289
9       births       life_expectancy -0.019662    0.019662
10  population     health_percentage -0.016296    0.016296
11      deaths     health_percentage -0.012450    0.012450
12  population       life_expectancy  0.006890    0.006890

    Variable X            Variable Y   Pearson  Intensidad
0   population                deaths  0.997836    0.997836
1       births                deaths  0.993034    0.993034
2   population                births  0.992562    0.992562
3       births  child_deaths_under_5  0.967222    0.967222
4       deaths  child_deaths_under_5  0.944894    0.944894
5   population  child_deaths_under_5  0.935124    0.935124
6       births                   gdp -0.044742    0.044742
7       births     health_percentage -0.030696    0.030696
8   population                   gdp -0.030289    0.030289
9       deaths                   gdp -0.028315    0.028315
10      births       life_expectancy -0.019662    0.019662
11  population     health_percentage -0.016296    0.016296
12      deaths     health_percentage -0.012450    0.012450
13  population       life_expectancy  0.006890    0.006890

    Variable X            Variable Y   Pearson  Intensidad
0   population                deaths  0.997836    0.997836
1       births                deaths  0.993034    0.993034
2   population                births  0.992562    0.992562
3       births  child_deaths_under_5  0.967222    0.967222
4       deaths  child_deaths_under_5  0.944894    0.944894
5   population  child_deaths_under_5  0.935124    0.935124
6       births                   gdp -0.044742    0.044742
7       births     health_percentage -0.030696    0.030696
8   population                   gdp -0.030289    0.030289
9       deaths                   gdp -0.028315    0.028315
10      births       life_expectancy -0.019662    0.019662
11  population     health_percentage -0.016296    0.016296
12      deaths     health_percentage -0.012450    0.012450
13  population       life_expectancy  0.006890    0.006890
14      deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6   child_deaths_under_5     health_percentage -0.049833    0.049833
7                 births                   gdp -0.044742    0.044742
8                 births     health_percentage -0.030696    0.030696
9             population                   gdp -0.030289    0.030289
10                deaths                   gdp -0.028315    0.028315
11                births       life_expectancy -0.019662    0.019662
12            population     health_percentage -0.016296    0.016296
13                deaths     health_percentage -0.012450    0.012450
14            population       life_expectancy  0.006890    0.006890
15                deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6   child_deaths_under_5                   gdp -0.062524    0.062524
7   child_deaths_under_5     health_percentage -0.049833    0.049833
8                 births                   gdp -0.044742    0.044742
9                 births     health_percentage -0.030696    0.030696
10            population                   gdp -0.030289    0.030289
11                deaths                   gdp -0.028315    0.028315
12                births       life_expectancy -0.019662    0.019662
13            population     health_percentage -0.016296    0.016296
14                deaths     health_percentage -0.012450    0.012450
15            population       life_expectancy  0.006890    0.006890
16                deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6   child_deaths_under_5       life_expectancy -0.067931    0.067931
7   child_deaths_under_5                   gdp -0.062524    0.062524
8   child_deaths_under_5     health_percentage -0.049833    0.049833
9                 births                   gdp -0.044742    0.044742
10                births     health_percentage -0.030696    0.030696
11            population                   gdp -0.030289    0.030289
12                deaths                   gdp -0.028315    0.028315
13                births       life_expectancy -0.019662    0.019662
14            population     health_percentage -0.016296    0.016296
15                deaths     health_percentage -0.012450    0.012450
16            population       life_expectancy  0.006890    0.006890
17                deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6      health_percentage                   gdp  0.193442    0.193442
7   child_deaths_under_5       life_expectancy -0.067931    0.067931
8   child_deaths_under_5                   gdp -0.062524    0.062524
9   child_deaths_under_5     health_percentage -0.049833    0.049833
10                births                   gdp -0.044742    0.044742
11                births     health_percentage -0.030696    0.030696
12            population                   gdp -0.030289    0.030289
13                deaths                   gdp -0.028315    0.028315
14                births       life_expectancy -0.019662    0.019662
15            population     health_percentage -0.016296    0.016296
16                deaths     health_percentage -0.012450    0.012450
17            population       life_expectancy  0.006890    0.006890
18                deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6      health_percentage       life_expectancy  0.286925    0.286925
7      health_percentage                   gdp  0.193442    0.193442
8   child_deaths_under_5       life_expectancy -0.067931    0.067931
9   child_deaths_under_5                   gdp -0.062524    0.062524
10  child_deaths_under_5     health_percentage -0.049833    0.049833
11                births                   gdp -0.044742    0.044742
12                births     health_percentage -0.030696    0.030696
13            population                   gdp -0.030289    0.030289
14                deaths                   gdp -0.028315    0.028315
15                births       life_expectancy -0.019662    0.019662
16            population     health_percentage -0.016296    0.016296
17                deaths     health_percentage -0.012450    0.012450
18            population       life_expectancy  0.006890    0.006890
19                deaths       life_expectancy -0.001312    0.001312

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6                    gdp       life_expectancy  0.675566    0.675566
7      health_percentage       life_expectancy  0.286925    0.286925
8      health_percentage                   gdp  0.193442    0.193442
9   child_deaths_under_5       life_expectancy -0.067931    0.067931
10  child_deaths_under_5                   gdp -0.062524    0.062524
11  child_deaths_under_5     health_percentage -0.049833    0.049833
12                births                   gdp -0.044742    0.044742
13                births     health_percentage -0.030696    0.030696
14            population                   gdp -0.030289    0.030289
15                deaths                   gdp -0.028315    0.028315
16                births       life_expectancy -0.019662    0.019662
17            population     health_percentage -0.016296    0.016296
18                deaths     health_percentage -0.012450    0.012450
19            population       life_expectancy  0.006890    0.006890
20                deaths       life_expectancy -0.001312    0.001312